icon: ':material-pulse:'
build:
  architectures:
    - amd64
    - aarch64
  variants:
    - tag: latest
      aliases: ["pkg-latest"]
      containerfile: Containerfile
      default: true
      args:
        BASE_VERSION: "15.1-latest"
cit:
  mode: screenshot
  port: 80
